---
- name: Build and run the helloworld Docker container
  hosts: localhost
  become: true
  tasks:
    - name: Build the Docker image
      command: docker build -t helloworld /projects/helloworld

    - name: Run the Docker container
      docker_container:
        name: helloworld
        image: helloworld
        state: started
        ports:
          - "8081:8080"